version: '3.3'

services: 
  
  docker-test:
    image: portfolio-2018
    container_name: portfolio-2018
    build:
      #the builds context is the set of files at a specified location
      #it is basically saying HEY look for my dockerfile at the base of the application
      context: .
      dockerfile: Dockerfile
      #how is volumes here different?
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '3000:3000'